### ISSUE TITLE
Brand New Things in WebAssembly Post-MVP Standard

### ISSUE THREAD

**Issue by TechQuery** [FreeCodeCamp-Chengdu/Web-Conf#16]
- 讲师：@Becavalier

**Comment by Samhanx** [comment]
本次大会的讲师于航（Jason Yu），除了在多个技术大会上布道之外，平时生活中也是一个极富情调的人。我们都亲切地称呼他为“于姐”。为什么呢？因为他不仅是个极客，还是传说中的“女装大佬”。访问于姐的  [Github 个人主页](https://github.com/Becavalier)，你就能看到他（她）的女装头像。更有甚者，于姐曾在参与某个开源项目时，被国外开发者误认为是个厉害的妹子。

于姐兴趣广泛。你时常能看到他发一些弹奏钢琴的短视频；也曾在公司组织团队成员练习街舞，参与演出；他甚至还是两只猫主子的铲屎官，一橘一花（其实主要是白色）。

橘猫叫皮卡丘，性子活泼，常常会在于姐准备 Coding 之时或趴或蹲在电脑前，一副求关爱的样子。
![image](https://user-images.githubusercontent.com/16429512/68354956-c0138800-0148-11ea-9166-c6bb1b4413c0.png)

花猫叫淘淘，性子文静，你如果看不到淘淘，那么不妨去看看于姐的床底。
![image](https://user-images.githubusercontent.com/16429512/68354930-aa9e5e00-0148-11ea-8064-6f404708b3b6.png)

看到这里，是不是觉得于姐妥妥的小说主角模板啊，有技术，有猫，还多才多艺。

于姐在今年早些时候出版了国内第一本系统介绍 WebAssembly 技术的书，《深入浅出 WebAssembly》。WebAssembly 是近年诞生的一门新技术，目前在国内还很少看到相关的应用和实践，这次他来分享 WebAssembly 相关的内容，想了解同学不容错过。

如果你想了解更多关于于姐的事情，可以看看我们之前对他做的一次访谈，[FCC DevTalk 002丨于航：happy coding, happy life](https://chinese.freecodecamp.org/forum/t/topic/187)，也欢迎大家支持于姐的书，《深入浅出 WebAssembly》。

**Comment by TechQuery** [comment]
https://docs.qq.com/slide/DTnhJYUN2dUhtWFRQ
