### ISSUE TITLE
SoLiD 社交互联数据 - 万维网之父的数据主权革命

### ISSUE THREAD

**Issue by TechQuery** [FreeCodeCamp-Chengdu/Web-Conf#18]
@leinue

**Comment by leinue** [comment]
这是需要我讲吗还是啥

**Comment by leinue** [comment]
> @leinue 我们非常希望您能来讲一下相关主题，本主题的直接对接人是 @TingYinHelen ，包括来成都的地接事宜

没问题啊，具体时间定下来了吗

**Comment by TingYinHelen** [comment]
11月16日 @leinue

**Comment by leinue** [comment]
> 11月16日 @leinue

It's OK

**Comment by TingYinHelen** [comment]
谢阳，本次年纪最小的讲师，96年小鲜肉，他在大二时开发了 Gospel，Gospel 提供了软件开发的全新解决方案。曾任职 好东西传送门的 CTO，目前在中国推广万维网之父的 SoLiD 项目，并基于此进行商业化试水。谢阳活跃于github，目前自己的创业项目Authing已经慢慢浮出水面，受到大家认可。年纪虽小，但是在初中的时候就开始编程，具有很强的编程能力和项目推动能力，十足的领导范儿。
自称：互联网之子

**Comment by leinue** [comment]
Presentation: https://github.com/leinue/solid-fcc-chengdu-2019

**Comment by TechQuery** [comment]
https://leinue.github.io/webfullstack-2019/
