### ISSUE TITLE
Enhanced Privacy with Decentralized Identity

### ISSUE THREAD

**Issue by TechQuery** [FreeCodeCamp-Chengdu/Web-Conf#19]
- 讲师：@Jack-Works

**Comment by yisiliu** [comment]
https://github.com/DimensionDev/Maskbook
https://github.com/DimensionDev/holoflows-kit

先发两个相应的 repo

**Comment by Jack-Works** [comment]
@TechQuery https://1drv.ms/p/s!Akj1fkJqOKOagoFfquScJlTlECRy7w?e=TNPobE

**Comment by TechQuery** [comment]
https://docs.qq.com/slide/DTkdHVXJScEJZZHFt
