### ISSUE TITLE
VI 设计、物料制作

### ISSUE THREAD

**Issue by TechQuery** [FreeCodeCamp-Chengdu/Web-Conf#20]
- 关键词：
  - 前端、客户端
  - 后端、Node.JS
  - 全栈
  - 开源、开放社群

**Comment by candycats** [comment]
添加初步物料表物料
2019年FCC全栈大会物料准备

参考2017、2018年的大会：

1、会场位置引导指示牌、演讲嘉宾介绍X展架
2、座位安排分布图、座位号牌（按票价区分）、会议议程表 +讲师有没有姓名牌
3、各展位宣传推广的易拉宝，桌椅
4、签到桌、签到二维码、午餐手环
5、矿泉水+赞助企业或公司宣传册（三折页广告）+会议邀请函或参会吊牌
6、礼品奖品（技术书籍、程序员周边）
7、硬件设施————大屏、演讲台、灯光、摄像、拍照、投影、笔记本电脑等电子设置
8、活动宣传横幅（合影用的，和会场外挂的）
9、会议热场音乐————《一人我编程累》音响、麦克风
10、会议背景板？（纤维布或高密度喷绘布、桁架）
11、茶歇（食品）
12、如果有抽奖，是以什么形式？ 是否需要准备 抽奖盒或者小程序
13、会议流程表
14、会议PPT
15、签到小礼品（前年我记得是小徽章？ 今年有没有什么会议资料之类的需要在签到时发给观众？）
16、主持人的串讲词或者手卡，是否需要打印
17、透明胶带、剪刀、笔

**Comment by zhangyanling77** [comment]
确认：
1、纸质赠票大概的数量
2、易拉宝数量：嘉宾+活动介绍+茶歇引导 
3、喷绘桁架 租借
4、自拍场景版是放置在哪个位置的，尺寸？是否需要支架
5、panky公仔大概的数量 
6、QA、抽奖礼品主要是哪种 程序员周边？技术书籍或者生发液，键盘鼠标等
7、茶歇 （甜点和果汁ok吧）

**Comment by Akagilnc** [comment]
> 确认：
> 1、纸质赠票大概的数量
> 2、易拉宝数量：嘉宾+活动介绍+茶歇引导
> 3、喷绘桁架 租借
> 4、自拍场景版是放置在哪个位置的，尺寸？是否需要支架
> 5、panky公仔大概的数量
> 6、QA、抽奖礼品主要是哪种 程序员周边？技术书籍或者生发液，键盘鼠标等
> 7、茶歇 （甜点和果汁ok吧）

@zhangyanling77 
1、目前需要的是10张，出于贵宾票和赠票的考虑。我考虑是200张左右。另外，纸质票，并非纸质赠票，纸质票只是电子票的实体，是不是赠票是我们说了算哈。
2、3（尺寸数量）、4、5、等我设计用户体验
6、以前是有书籍，这次可以考虑的事，书籍，公仔，或者赞助商赞助的礼品物料
7、ok的。不过具体要看价格和东西的样图

**Comment by zhangyanling77** [comment]
1.喷绘桁架 3*5 租借2天 1500
2.自拍板 60一平
3.x展架 
60*160 35 （这种更合适）20个
80*180  40
4.票500张 380
5.横幅 8元一米 
6.600个纸袋 2元左右一个 （淘宝）
7.手环 1-1.5元一个 （淘宝）
8.提词卡 
9.水 1元 1000+
10.茶歇 两天 3200*2 = 6400
11.公仔 300个 34*300+500 = 10700
