### ISSUE TITLE
ECMAScript 标准最新进展

### ISSUE THREAD

**Issue by TechQuery** [FreeCodeCamp-Chengdu/Web-Conf#22]
@hax

**Comment by hax** [comment]
这是11月份在成都的会议？

**Comment by TechQuery** [comment]
11月16日，非常希望贺老来讲

**Comment by hax** [comment]
好的。

**Comment by TechQuery** [comment]
@hax 贺老得空填一下讲师信息表哈 https://jinshuju.net/f/86DawT

**Comment by Cute233** [comment]
收

**Comment by Cute233** [comment]
宣传文案版本1: hax，资料详情，自己去搜吧，但是参加的技术会议有上海，台湾，北京，深圳…这次是成都！演讲过的内容有……，有点多。这次是最新的ECMAScript进阶，其中包括JS 最新的 proposal 介绍，有：提案的目的、用例、对开发者的影响、尚待解决的问题、采纳中需要注意的点…最新，最新！跟上节奏就完事～

**Comment by Cute233** [comment]
版本2:
最近收到任务，要写宣传文。没有文采的我，想了好久也没有想出来，太南了

好不容易想了个大纲，但是内容要填充呢
咋个办呦？

我的大纲如下：
hax，资料详情，自己去搜吧😛，但是参加的技术会议有上海，台湾，北京，深圳…这次是成都！演讲的内容有…………，这次是最新的语言标准，最新！跟上节奏就完事～

大纲想好了，得保证真实性呀，我得去百度或者bing呀～

但是，
   没有搜全他去过哪些地方参加会议啊！
啊，太南了，我还是问问贺佬本人吧

然后贺佬给了我一个链接.,简洁而有力的回答,比我搜那么近的信息还全还真还明了,哈哈哈哈哈

嗯，我点看链接（http://johnhax.net/events）一看，打扰了，果然真大佬！

是这样的，我要的内容都有！哈哈哈哈哈

**Comment by Cute233** [comment]
版本2:
最近收到任务，要写宣传文。没有文采的我，想了好久也没有想出来，太南了

好不容易想了个大纲，但是内容要填充呢
咋个办呦？

我的大纲如下：
hax，资料详情，自己去搜吧😛，但是参加的技术会议有上海，台湾，北京，深圳…这次是成都！演讲的内容有…………，这次是最新的语言标准，最新！跟上节奏就完事～

大纲想好了，得保证真实性呀，我得去百度或者bing呀～

但是，
   没有搜全他去过哪些地方参加会议啊！
啊，太南了，我还是问问贺佬本人吧

然后贺佬给了我一个链接.,简洁而有力的回答,比我搜那么近的信息还全还真还明了,哈哈哈哈哈

嗯，我点看链接（http://johnhax.net/events）

一看，打扰了，果然真大佬！

是这样的，我要的内容都有！哈哈哈哈哈

**Comment by Cute233** [comment]
版本3:今有大佬来蓉分享,穿过大山越过小巷.  最新语标,最新proposal. 前座买票一睹风采,庭前一席胜十书.

**Comment by TechQuery** [comment]
https://johnhax.net/2019/js-this/slide
