### ISSUE TITLE
场地方、赞助商、参展商

### ISSUE THREAD

**Issue by TechQuery** [FreeCodeCamp-Chengdu/Web-Conf#23]

**Comment by demongodYY** [comment]
![img](https://fcc-cd.tk/images/FCC-CDC-v1-0.png)
# 共创伙伴招募 | FCC 成都 2019

## **/ 我们是谁 /**     

- 成都“家门口”的公益性开发者社区。
- 秉承“人人皆可编程”的理念，致力于重塑编程教育，以极客独特的方式为城市带来美好改变。
- 以帮助成都公益组织完成项目、帮助大学生积累经验 、帮助企业培养人才为目的。
- 面向成都所有愿意学习编程、热爱编程、以及想要通过编程找到一份好工作的学生或社会群众。



## **/ 我们做过什么/**  

过去2年，经 freeCodeCamp 总部授权，我们在成都举办过500+人以上规模技术盛会四次，以**技术分享**、**黑客马拉松**为主，并集合了**企业招聘**、**企业产品展台**、**开源市集**等多个环节，为参会者带来了高标准的体验：

- [2017成都 Web 前端大会](https://web-conf.tk/2017/)
- [新耀杯 Code for City 黑客马拉松](http://www.itdks.com/Home/Act/apply?mUid=3049982&id=2007)
- [2018 成都 React 专题大会](https://ppt.baomitu.com/conference/60)
- [2018成都 Web 前端大会](https://web-conf.tk/2018/)



## **/ 接下来/**     

2019 年，FCC 成都将于11月16日举办【2019成都 Web 全栈年度大会】。此次大会，我们希望打破”前端开发“这个限制，为所有参会者、开发者提供更加丰富、多元化的技术体验。为此，我们也期待有更多伙伴或机构能参与共创，包括不限于**品牌共创、内容共创、体验共创、媒体共创**等。



## **/ 共创需求 /**     

**品牌共创**

- 说明：换言之，即是我们的赞助商。
- 我们的需求：现金赞助；或者场地、酒店、餐食、礼品、交通、搭建、设计、印刷、制作等物资或服务。
- 我们可以回馈：对应的品牌广告价值。可能包括：冠名、专属企业展台、企业资料入袋、企业与观众互动环节等。



**内容共创**

- 说明：本次活动技术分享内容
- 我们的需求：推荐技术分享话题及讲师
- 我们可以回馈：精准的社区资源，讲师个人品牌价值
- [讲师报名入口](https://jinshuju.net/f/86DawT)

**体验共创**

- 说明：本次活动外场设计有企业产品体验展台、企业招聘展台以及开源项目市集。
- 我们的需求：良好的企业产品体验展示、企业招聘者、开源项目宣传者者
- 我们可以回馈：精准的社区资源；受限的品牌广告价值。

**媒体共创**

- 说明：除了传统的媒体合作外，还需要新媒体领域的合作。

- 我们的需求：稿件采写；活动报道与分发；照片拍摄；创意短片策划；动画制作等。

- 我们可以回馈：对应的品牌广告价值。

  
## **/ 联系我们 /**     

**微信 ：** 
![image](https://user-images.githubusercontent.com/17036920/65339684-3262f400-dbff-11e9-8c80-5b5f1f59a183.png)

**邮箱：** 
yyuuqqii@outlook.com

**或者留言给【FCC成都社区】公众号，我们将有专门的工作人员对接**
