### ISSUE TITLE
志愿者招募、培训、管理

### ISSUE THREAD

**Issue by Akagilnc** [FreeCodeCamp-Chengdu/Web-Conf#25]

**Comment by TechQuery** [comment]
## 反思
1. 参照【讲师征集表单】，提前收集志愿者信息
2. 会议结束前，任何工作人员不得私自决定**奖品调换**、**福利分配**

**Comment by HillChen3** [comment]
1. 每次会议需要提前布展，但因为工作时间比较尴尬，以后应该准备一个工作日也能安排时间的小组负责布展等问题。
2. 志愿者不需要招募太多，社区成员每次到场并分工明确，基本可以覆盖所有问题。

**Comment by HillChen3** [comment]
3. 摄影以后还是需要安排专业的志愿者进行负责。前期安排工作的时候遗漏了这个问题。

**Comment by TechQuery** [comment]
工作日也能来布展的只有大学生了，还好这次场地方先摆好了椅子，展位桌子也很好推
