### ISSUE TITLE
DevCloud Web Components 实践

### ISSUE THREAD

**Issue by TechQuery** [FreeCodeCamp-Chengdu/Web-Conf#33]
- 讲师：@myzhibie

**Comment by kitety** [comment]
慕阳老师，六年开发经验，曾任职美团、人人网，现任华为云高级前端。听到这样的大佬名号，萌新的我真是瑟瑟发抖。直到我看到他发给我的这样一张图片：
 
![pasted image 0](https://user-images.githubusercontent.com/22906933/67954716-5f59ec00-fc2c-11e9-9d16-df94dab13022.png)
https://i.loli.net/2019/10/31/cBkGoby42Aef1CZ.png

没错就是这只自带“眼罩”大懒猫，我才真实的感觉到他也是一个热爱生活的人。他并不是大家想象中的两耳不闻窗外事，一心钻研搞技术的宅男；他也是爱刷抖音，爱跑步，没事撸撸猫，看看电影，外加陪陪女朋友的人。太真实了有木有！

可能有的同学了解过Web Components，但实际使用比较多的都是类似于Vue或React形式的组件。所以大家非常好奇老师将会在这次大会中给我们带来哪些关于Web Components的黑科技。

我们已经了解到，老师将以华为云内部复杂的前端业务为背景，结合在实际项目中使用Web Components的一些经验，为我们带来一期干货满满的Web Components实践分享。希望同学们带好小本本，好好写笔记，一定会有很多收获哦！

**Comment by TechQuery** [comment]
https://docs.qq.com/slide/DTnlwYmFham56YkFI
