### ISSUE TITLE
蚂蚁前端研发最佳实践

### ISSUE THREAD

**Issue by TechQuery** [FreeCodeCamp-Chengdu/Web-Conf#39]
- 讲师：@sorrycc

**Comment by phobal** [comment]
![](https://img.alicdn.com/tfs/TB1ia0HdHr1gK0jSZFDXXb9yVXa-1783-2675.jpg)

陈成，网名：sorrycc，花名：云谦。阿里巴巴 P8 高级技术专家。毕业于浙江大学，已是 2 孩子（男孩）的爸爸。
2008 年 sorrycc 每个月拿着 4000 钱在一家小公司打杂，希望老板加薪 500 元， 老板都不肯，一气之下加入了阿里，一待就待到现在，前 5 年在淘宝 UED 工作，负责淘宝首页、宝贝详情、购物车和下单等很多重要的前端业务开发，后转岗到支付宝，目前在玉伯带领的蚂蚁前端体验技术部，为现代前端开发输出了源源不断的设计和技术。截止目前已开源了众多颠覆性的项目，包括不限于 [dva](https://github.com/dvajs/dva) - 基于 redux 和 redux-saga 的数据流解决方案（14K）、[umi](https://github.com/umijs/umi) - 可插拔的企业级 react 应用框架（6.2K）、[roadhog](https://github.com/sorrycc/roadhog) - 开箱即用的 react 应用开发工具（2.5K），以及造福全球数以万计的中小企业搭建后台管理系统的组件库 [ant-design](https://github.com/ant-design/ant-design/) （53K）。本次有幸请到 sorrycc 大佬来成都参加由 FCC 和  阿里云联合举办的 2019 成都 Web 全栈大会，他将带来 《蚂蚁前端研发最佳实践》主题演讲，主要给大家分享一下蚂蚁前端在语言、CSS、目录结构、路由、数据流、Mock、构建工具、组件开发、测试、性能优化微前端等方面选择的最佳实践，以及最佳实践的迭代、遇到的问题、挑战和他的思考。

**Comment by TechQuery** [comment]
https://docs.qq.com/slide/DTllLRUx6b0N3bnZi
