### ISSUE TITLE
网站界面国际化

### ISSUE THREAD

**Issue by TechQuery** [FreeCodeCamp-Chengdu/Web-Conf#52]
## 目标文件夹

https://github.com/FreeCodeCamp-Chengdu/Web-Conf/tree/master/source%2Fi18n

## 上游开源库

https://github.com/idea2app/MobX-i18n

**Comment by TechQuery** [comment]
> 我看了内容，感觉上没有看懂，不知道具体有什么要求。我进入了目标文件夹，看了三个代码，感觉上没有明白，所以，我不知道有什么要求需要我写代码。

先说一下你的理解和具体哪里不懂，我才知道怎么教你。

@luojiyin1987 在群里发的这张截图所示的探索方式，你有没有尝试？

![1722606370517.jpg](https://github.com/user-attachments/assets/fc3e3994-f1a4-41bc-9adb-d013d92932be)

**Comment by douxiaobo** [comment]
我记得，以前，我看了主题：Issue模板从Markdown改为YAML格式，这个主题，我看懂了，但是，今天，我看了主题：网站界面国际化，我感觉上没看懂，不知道具体内容，我有时候猜想是什么意思，猜想做什么，我猜想，我是不是要做翻译？

目标文件夹，我进入以后，打开看看三个TypeScript代码文件，我大脑里一片空白，我不知道用三个文件做什么，不是我从来没有学过TypeScript,也不是我看不懂TypeScript，而是我没有问题，一边学习TypeScript，一边在三个 TypeScript代码文件写代码，
但是，我很迷茫，不知道做什么，我看了主题网站界面国际化，我不是很懂。

我看了上游开源库的内容，我知道是学习新的知识。

我在飞书的群里看到luojiyin1987的截图，我以为是他可能发给所有人看一看。我看了图片，我不是这个意思，我不是搜索。

我可能讲得没有清楚，比较难讲，我就是不知道在工作上要做什么，也不知道需求是什么。Issue模板从Markdown改为YAML格式，我知道，在工作上做什么，就是把Markdown代码上理解一下，然后在YAML写代码从Markdown转过来，我也知道，需求是生成新的YAML格式。

**Comment by TechQuery** [comment]
> 但是，今天，我看了主题：网站界面国际化，我感觉上没看懂，不知道具体内容，我有时候猜想是什么意思，猜想做什么，我猜想，我是不是要做翻译？
> 
> 目标文件夹，我进入以后，打开看看三个TypeScript代码文件，我大脑里一片空白，我不知道用三个文件做什么

三个文件（其实需要改的是 `en-US.ts` 和 `zh-CN.ts`）哪些一样、哪些不一样？左边的键名一样，右边的字符串不一样。也就是同样的位置在不用语言要显示不同的文本，自然是”翻译“，即”界面国际化“关键词 Google 出来的 Internationalization（简称 i18n），所以才有 MobX-i18n 开源库。

> 我在飞书的群里看到luojiyin1987的截图，我以为是他可能发给所有人看一看。我看了图片，我不是这个意思，我不是搜索。

不要”以为“，看到内含相同内容就去照猫画虎地试验，然后不懂就问。群里问多了，我不行一天解决不了”不懂需求“这种概念层面的问题。
